apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: production-mon-ingress
  namespace: general-healthchk
spec:
  rules:
  - host: healthchk.qcluster.org
    http:
      paths:
      - backend:
          serviceName: k8s-production-mon
          servicePort: 5035
        path: /
