apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: gluster-cap-admin
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/glusterfs
  name: k8s-production-mon
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
