# Default values for elasticsearch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
appVersion: "22c3def9"
phase: staging-dev
name: toman-staging-dev
namespace: toman-staging-dev
image:
  repository: "registry.hamdocker.ir/qbit/backend"
  tag: "22c3def9"
  pullPolicy: "Always"
  # If specified, use these secrets to access the image
  # pullSecrets:
  #   - registry-secret


initImage:
  name: init-qbit
  repository: "registry.hamdocker.ir/qbit/backend"
  tag: "22c3def9"
  pullPolicy: "Always"

storage:
  media: "media"
  statics: "statics"

database:
  user: "qbit-staging"
  db_host:  "pg.qcluster.org"
  db_name: "qpay-staging"
  hc_db_name: "hc-qpay-staging"

deployment:
  entrypoint: "web"
  debug: "False"
  phase: "staging"
  replicas: 1
  antiAffinity: "soft"
  nodeAffinity: {}
  nodeSelector: {}
  tolerations: []
  initResources: {}
    # limits:
    #   cpu: "25m"
    #   # memory: "128Mi"
    # requests:
    #   cpu: "25m"
    #   memory: "128Mi"
  resources:
    limits:
      cpu: "0.5"
      memory: "1Gi"
    requests:
      cpu: "0.5"
      memory: "1Gi"
  priorityClassName: ""
  ## (dict) If specified, apply these annotations to each client Pod
  # podAnnotations:
  #   example: client-foo
  podDisruptionBudget:
    enabled: false
    minAvailable: 2
    maxUnavailable: 1

